-- 테이블 초기화
-- 제약조건 때문에 USERINFO는 맨 마지막에 지워야합니다.
DELETE FROM TASK;
DELETE FROM USERINFO;

-- SEQUENCE 초기화
ALTER SEQUENCE SEQUENCE_USERID RESTART START WITH 1;
ALTER SEQUENCE SEQUENCE_POSTID RESTART START WITH 1;
ALTER SEQUENCE SEQUENCE_POST_TASK RESTART START WITH 1;
ALTER SEQUENCE SEQUENCE_TASKID RESTART START WITH 1;